name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github Registry
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: |
          olegtarasov/inspector:latest
